config/routes.rb
Rails.application.routes.draw do
  resources :artist_instruments
  resources :instruments
  resources :artists
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :artist_instruments, dependent: :destroy
    has_many :instruments, through: :artist_instruments
end

app/models/artist_instrument.rb
class ArtistInstrument < ApplicationRecord
  belongs_to :artist
  belongs_to :instrument
end

app/models/instrument.rb
class Instrument < ApplicationRecord
    has_many :artist_instruments, dependent: :destroy
    has_many :artists, through: :artist_instruments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artist_instruments_controller.rb
class ArtistInstrumentsController < ApplicationController

    def index 
        @artist_instruments = ArtistInstrument.all 
    end

    def new
        @artists = Artist.all
        @instruments = Instrument.all
    end

    def create 
        ArtistInstrument.create(artist_instrument_params)
        redirect_to artist_instruments_path
    end

    def destroy
        @artist_instrument = ArtistInstrument.find(params[:id])
        @artist_instrument.destroy
        redirect_to artist_instruments_path
    end

    private

    def artist_instrument_params
        params.require(:artist_instrument).permit(:artist_id,:instrument_id)
    end
end

app/controllers/artists_controller.rb
=begin

This is the artist controller

=end

class ArtistsController < ApplicationController
    before_action :find_artist, only: [:show, :edit, :update, :destroy]

    def index 
        @artists = Artist.all
    end

    def show
    end

    def new
    end

    def create 
        @artist = Artist.create(artist_params)
        redirect_to artist_path(@artist)
    end

    def edit 
    end

    def update 
        @artist.update(artist_params)
        redirect_to artist_path(@artist)
    end

    def destroy 
        @artist.destroy
        redirect_to artists_path
    end

    private

    def artist_params
        params.require(:artist).permit(:name)
    end

    def find_artist
        @artist = Artist.find(params[:id])
    end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
    before_action :find_instrument, only: [:show, :edit, :update, :destroy]

    def index 
        @instruments = Instrument.all
    end

    def show
    end

    def new
    end

    def create 
        @instrument = Instrument.create(instrument_params)
        redirect_to instrument_path(@instrument)
    end

    def edit 
    end

    def update 
        @instrument.update(instrument_params)
        redirect_to instrument_path(@instrument)
    end

    def destroy 
        @instrument.destroy
        redirect_to instruments_path
    end

    private

    def instrument_params
        params.require(:instrument).permit(:name)
    end

    def find_instrument
        @instrument = Instrument.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_instruments_helper.rb
module ArtistInstrumentsHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/artist_instruments/index.html.erb
<h1>ArtistInstruments</h1>
<ul>
  <% @artist_instruments.each do |artist_instrument| %>
    <%= link_to artist_instrument.artist.name, artist_path(artist_instrument.artist) %> - 
    <%= link_to artist_instrument.instrument.name, instrument_path(artist_instrument.instrument) %> - 
    <%= button_to "Delete ArtistInstrument", artist_instrument_path(artist_instrument), method: :delete %>
  <% end %>
</ul>
<%= link_to "New Artist-Instrument Form", new_artist_instrument_path %>

app/views/artist_instruments/new.html.erb
<h1>ArtistInstrument Form</h1>
<%= form_with model: ArtistInstrument.new do |form|  %>
  Artist: <%= form.collection_select :artist_id, @artists, :id, :name, include_blank: true, id: "artist"  %>
</br></br>
Instrument: <%= form.collection_select :instrument_id, @instruments, :id, :name, include_blank: true, id: "instrument"  %>
</br></br>
<%= form.submit "Submit" %>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist Page</h1>
<%= form_with model: @artist, url: artist_path(@artist), method: :patch, local: true, scope: :artist do |form| %>
  <%= form.text_field :name, id: :name %>
  <%= form.submit "Submit" %>
<% end %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>
<%= link_to "New Artist Form", new_artist_path %>
</br>
<%= link_to "New Artist-Instrument Form", new_artist_instrument_path %>

app/views/artists/new.html.erb
<h1>Artist Form</h1>
<%= form_with model: Artist.new do |form| %>
  <%= form.text_field :name, id: :name %>
  <%= form.submit "Submit"  %>
<% end %>

app/views/artists/show.html.erb
<h1>Artist Page</h1>
<%= @artist.name %>
<br/>
<% @artist.instruments.each do |instrument| %>
  <li><%= link_to instrument.name, instrument_path(instrument) %></li>
<% end %>
<br/>
<br/>
<%= link_to "Edit Artist", edit_artist_path(@artist), method: :get %>
<br/>
<br/>
<%= button_to "Delete Artist", artist_path(@artist), method: :delete %>
<br/>
<br/>
<%= link_to "Index", artists_path %>

app/views/instruments/edit.html.erb
<h1>Edit Instrument Page</h1>
<%= form_with model: @instrument, url: instrument_path(@instrument), method: :patch, local: true, scope: :instrument do |form| %>
  <%= form.text_field :name, id: :name %>
  <%= form.submit "Submit" %>
<% end %>

app/views/instruments/index.html.erb
<h1>Instruments</h1>
<ul>
  <% @instruments.each do |instrument| %>
    <li><%= link_to instrument.name, instrument_path(instrument) %></li>
  <% end %>
</ul>
<%= link_to "New Instrument Form", new_instrument_path %>
</br>
<%= link_to "New Artist-Instrument Form", new_artist_instrument_path %>

app/views/instruments/new.html.erb
<h1>Instrument Form</h1>
<%= form_with model: Instrument.new do |form| %>
  <%= form.text_field :name, id: :name %>
  <%= form.submit "Submit" %>
<% end %>

app/views/instruments/show.html.erb
<h1>Instrument Page</h1>
<%= @instrument.name %>
<br/>
<% @instrument.artists.each do |artist| %>
  <li><%= link_to artist.name, artist_path(artist) %></li>
<% end %>
<br/>
<br/>
<%= link_to "Edit Instrument", edit_instrument_path(@instrument), method: :get %>
<br/>
<br/>
<%= button_to "Delete Instrument", instrument_path(@instrument), method: :delete %>
<br/>
<br/>
<%= link_to "Index", instruments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicSchool</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>